on:
  push:
    tags:
      - 'v*'

name: Release Mod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: echo ${{ github.ref }}
      - name: Build
        uses: eskatos/gradle-command-action@v1.3.2
        with:
          gradle-version: wrapper
          arguments: check build --stacktrace
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        with:
          files: build/libs/*.jar
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}